// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Link from "next/link";
// import { Roboto, Work_Sans } from "next/font/google";




// const roboto = Roboto({
//   subsets: ["latin"],
//   variable: "--font-roboto",
// });

// const workSans = Work_Sans({
//   subsets: ["latin"],
//   variable: "--font-work-sans",
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: {
//     default: "Digital Platform",
//     template: "%s | Next.js",
//   },
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{ children: React.ReactNode }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className={`${roboto.variable} ${workSans.variable}`}>
    


//         <ul className="flex flex-row flex-nowrap bg-[#d1e7f0] text-black p-4 rounded-lg shadow-lg mt-4 mb-4 mx-4 sm:mx-8 justify-start overflow-x-auto whitespace-nowrap gap-2 lg:gap-56">
//   <li className="text-lg lg:text-xl  hover:scale-150 transition-all duration-300">
//     <Link href="/">Home</Link>
//   </li>
//   <li className="text-lg lg:text-xl hover:scale-150 transition-all duration-300">
//     <Link href="/about">About</Link>
//   </li>
//    <li className="text-lg lg:text-xl hover:scale-150 transition-all duration-300">
//     <Link href="/contact">Contact</Link>
//   </li>
// </ul>


//         {/* Main Content */}
//         <div>{children}</div>

//         {/* Footer */}
//         <footer className="bg-[#d1e7f0] text-white py-12">
//           <div className="container mx-auto px-4 flex flex-col md:flex-row justify-between items-start">
//             <div className="footer-left flex-1 max-w-[40%] mb-6 md:mb-0">
//               <p className="text-black mb-6">
//                 We provide a seamless platform for businesses without their own website to showcase their catalogs, 
//                 projects, and company information. By uploading your catalog or project PDF, you can display your products and services in a professional, 
//                 easily accessible format. Whether you're a small business or a large corporation, our service helps you reach your audience effectively, without the need for a full-fledged website.
//               </p>
//               <div className="social-icons flex space-x-4 text-black">
           
//                 <a href="https://www.linkedin.com/in/mokanijay/?skipRedirect=true" className="text-white hover:text-[#f5a623]">
//                   <i className="fab fa-linkedin-in"></i>
//                 </a>
//                 <a href="https://x.com/MokaniJay" className="text-white hover:text-[#f5a623]">
//                   <i className="fab fa-twitter"></i>
//                 </a>
//                 <a href="https://www.instagram.com/mokani_jay_/" className="text-white hover:text-[#f5a623]">
//                   <i className="fab fa-instagram"></i>
//                 </a>
//               </div>
//             </div>
            

//             <div className="footer-right flex-1 max-w-[20%]">
//               <h3 className="text-xl text-black font-semibold mb-4">Quick Links</h3>
//               <ul>
//                 <li className="mb-2 text-black">
//                   <Link href="/about" className="hover:text-[#f5a623]">
//   What We Do
// </Link>
//                 </li>
               
//                 {/* <li className="mb-2">
//                   <Link href="#">
//                     <a className="hover:text-[#f5a623]">Contact Us</a>
//                   </Link>
//                 </li> */}
//                 {/* <li className="mb-2">
//                   <Link href="#">
//                     <a className="hover:text-[#f5a623]">Product Gallery</a>
//                   </Link>
//                 </li> */}
//               </ul>
//             </div>
//           </div>

//           <div className="footer-bottom text-center text-black mt-6">
//             <p className="text-sm">© 2025. All Rights Reserved | Website</p>
//           </div>
//         </footer>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Roboto, Work_Sans } from "next/font/google";




const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});

// The following Geist font imports and definitions were removed to fix the unused variable warnings.
// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: {
    default: "Digital Platform",
    template: "%s | Next.js",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} ${workSans.variable}`}>
    


        <ul className="flex flex-row flex-nowrap bg-[#d1e7f0] text-black p-4 rounded-lg shadow-lg mt-4 mb-4 mx-4 sm:mx-8 justify-start overflow-x-auto whitespace-nowrap gap-2 lg:gap-56">
  <li className="text-lg lg:text-xl  hover:scale-150 transition-all duration-300">
    <Link href="/">Home</Link>
  </li>
  <li className="text-lg lg:text-xl hover:scale-150 transition-all duration-300">
    <Link href="/about">About</Link>
  </li>
   <li className="text-lg lg:text-xl hover:scale-150 transition-all duration-300">
    <Link href="/contact">Contact</Link>
  </li>
</ul>


        {/* Main Content */}
        <div>{children}</div>

        {/* Footer */}
        <footer className="bg-[#d1e7f0] text-white py-12">
          <div className="container mx-auto px-4 flex flex-col md:flex-row justify-between items-start">
            <div className="footer-left flex-1 max-w-[40%] mb-6 md:mb-0">
              <p className="text-black mb-6">
                We provide a seamless platform for businesses without their own website to showcase their catalogs, 
                projects, and company information. By uploading your catalog or project PDF, you can display your products and services in a professional, 
                easily accessible format. Whether **you&apos;re** a small business or a large corporation, our service helps you reach your audience effectively, without the need for a full-fledged website.
              </p>
              <div className="social-icons flex space-x-4 text-black">
           
                <a href="https://www.linkedin.com/in/mokanijay/?skipRedirect=true" className="text-white hover:text-[#f5a623]">
                  <i className="fab fa-linkedin-in"></i>
                </a>
                <a href="https://x.com/MokaniJay" className="text-white hover:text-[#f5a623]">
                  <i className="fab fa-twitter"></i>
                </a>
                <a href="https://www.instagram.com/mokani_jay_/" className="text-white hover:text-[#f5a623]">
                  <i className="fab fa-instagram"></i>
                </a>
              </div>
            </div>
            

            <div className="footer-right flex-1 max-w-[20%]">
              <h3 className="text-xl text-black font-semibold mb-4">Quick Links</h3>
              <ul>
                <li className="mb-2 text-black">
                  <Link href="/about" className="hover:text-[#f5a623]">
  What We Do
</Link>
                </li>
               
                {/* <li className="mb-2">
                  <Link href="#">
                    <a className="hover:text-[#f5a623]">Contact Us</a>
                  </Link>
                </li> */}
                {/* <li className="mb-2">
                  <Link href="#">
                    <a className="hover:text-[#f5a623]">Product Gallery</a>
                  </Link>
                </li> */}
              </ul>
            </div>
          </div>

          <div className="footer-bottom text-center text-black mt-6">
            <p className="text-sm">© 2025. All Rights Reserved | Website</p>
          </div>
        </footer>
      </body>
    </html>
  );
}